import type { RabbitDataGenerator } from '../generators/RabbitDataGenerator';

interface Config {
  vhost: string;
  globalParameters: { name: string, value: string }[];
}

export const terraformExporter = (generator: RabbitDataGenerator, config: Config): string => {
  const exchanges = generator.getExchanges();
  const queues = generator.getQueues();
  const routings = generator.getRoutings();

  const exchangesResources = exchanges.map(exchange => `
resource "rabbitmq_exchange" "${exchange.name}" {
  name  = "${exchange.name}"
  vhost = rabbitmq_vhost.rabbitmq.name

  settings {
    type        = "${exchange.type}"
    durable     = ${exchange.durable}
    auto_delete = ${exchange.autoDelete}
  }
}
`);

  const queuesResources = queues.map(queue => `
resource "rabbitmq_queue" "${queue.name}" {
  name = "${queue.name}"
  vhost = rabbitmq_vhost.rabbitmq.name
  
  settings {
    durable = ${queue.durable}
    auto_delete = ${queue.autoDelete}
    arguments_json = <<EOF
${JSON.stringify(queue.arguments, null, 2)}
EOF
  }
}
`);

  const routingResources = routings.map((routing, i) => `
resource "rabbitmq_binding" "b${i}" {
  source = rabbitmq_exchange.${routing.source}.name
  vhost = rabbitmq_vhost.rabbitmq.name
  destination = rabbitmq_queue.${routing.destination}.name
  destination_type = "${routing.destinationType}"
  routing_key = "${routing.routingKey}"
}  
`);

  const docs = `
# === Autogenerated by 'rabbitmq-defgen' ======================
# === Don't change manually, use original application to regenerate that file
`;

  const vHostConfig = `
resource "rabbitmq_vhost" "rabbitmq" {
  name = var.prefix
}

resource "random_password" "rabbitmq" {
  length  = 64
  special = false
}

resource "rabbitmq_user" "rabbitmq" {
  name     = var.prefix
  password = random_password.rabbitmq.result
}

resource "rabbitmq_permissions" "permissions" {
  user  = rabbitmq_user.rabbitmq.name
  vhost = rabbitmq_vhost.rabbitmq.name

  permissions {
    configure = ".*"
    write     = ".*"
    read      = ".*"
  }
}
`;

  return `
${docs}
${vHostConfig}
${exchangesResources.join('\n')}
${queuesResources.join('\n')}
${routingResources.join('\n')}  
`;
};